In [1]:
from fastai.tabular.all import *

In [3]:
import pandas as pd
from pycaret.datasets import get_data

data = get_data('wine') 
data.to_csv('wine.csv')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [9]:
dls = TabularDataLoaders.from_df(data, y_names="type",
    cat_names = ['quality'],
    cont_names = ['fixed acidity', 'volatile acidity',
                 'citric acid', 'residual sugar',
                 'chlorides', 'free sulfur dioxide',
                 'total sulfur dioxide', 'density',
                 'pH', 'sulphates', 'alcohol'],
    procs = [Categorify, FillMissing, Normalize])

In [10]:
learn = tabular_learner(dls, metrics=accuracy)

In [11]:
learn.fit_one_cycle(1)

In [12]:
learn.show_results()

In [16]:
row, clas, probs = learn.predict(data.iloc[5])

In [17]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red